<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'breadbottomside' => '/src/ingredients/BreadBottomSide.php',
                'breadtopside' => '/src/ingredients/BreadTopSide.php',
                'burger' => '/src/Burger.php',
                'burgerbuilder' => '/src/BurgerBuilder.php',
                'burgerbuildertest' => '/tests/BurgerBuilderTest.php',
                'cheese' => '/src/ingredients/Cheese.php',
                'cheeseburgerrecipe' => '/src/CheeseburgerRecipe.php',
                'hamburgerrecipe' => '/src/HamburgerRecipe.php',
                'ingredient' => '/src/Ingredient.php',
                'ingredientcollection' => '/src/IngredientCollection.php',
                'ingredientfactorytest' => '/tests/IngredientFactoryTest.php',
                'ingredientinterface' => '/src/IngredientInterface.php',
                'ingredientnamecollection' => '/src/IngredientNameCollection.php',
                'ingredientrepository' => '/src/IngredientRepository.php',
                'ingredienttest' => '/tests/IngredientTest.php',
                'patty' => '/src/ingredients/Patty.php',
                'recipeinterface' => '/src/RecipeInterface.php',
                'recipetest' => '/tests/RecipeTest.php',
                'salad' => '/src/ingredients/Salad.php',
                'sauce' => '/src/ingredients/Sauce.php',
                'tomatoe' => '/src/ingredients/Tomatoe.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
