<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'breadbottomside' => '/src/ingredients/BreadBottomSide.php',
                'breadtopside' => '/src/ingredients/BreadTopSide.php',
                'burger' => '/src/Burger.php',
                'burgerbuilder' => '/src/BurgerBuilder.php',
                'burgerbuildertest' => '/tests/BurgerBuilderTest.php',
                'burgertest' => '/tests/BurgerTest.php',
                'burgerviewmodel' => '/src/BurgerViewModel.php',
                'cheese' => '/src/ingredients/Cheese.php',
                'cheeseburgerrecipe' => '/src/CheeseburgerRecipe.php',
                'chfcurrency' => '/src/ChfCurrency.php',
                'chfcurrencytest' => '/tests/ChfCurrencyTest.php',
                'currencyinterface' => '/src/CurrencyInterface.php',
                'hamburgerrecipe' => '/src/HamburgerRecipe.php',
                'ingredient' => '/src/Ingredient.php',
                'ingredientcollection' => '/src/IngredientCollection.php',
                'ingredientcollectiontest' => '/tests/IngredientCollectionTest.php',
                'ingredientinterface' => '/src/IngredientInterface.php',
                'ingredientnamecollection' => '/src/IngredientNameCollection.php',
                'ingredientnamecollectiontest' => '/tests/IngredientNameCollectionTest.php',
                'ingredientrepository' => '/src/IngredientRepository.php',
                'ingredientrepositorytest' => '/tests/IngredientRepositoryTest.php',
                'ingredienttest' => '/tests/IngredientTest.php',
                'patty' => '/src/ingredients/Patty.php',
                'price' => '/src/Price.php',
                'pricetest' => '/tests/PriceTest.php',
                'recipe' => '/src/Recipe.php',
                'recipeinterface' => '/src/RecipeInterface.php',
                'recipetest' => '/tests/RecipeTest.php',
                'renderer' => '/src/Renderer.php',
                'salad' => '/src/ingredients/Salad.php',
                'sauce' => '/src/ingredients/Sauce.php',
                'tomato' => '/src/ingredients/Tomato.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
